Develop
AlexCuse/watermill-pulsar pull request #2
Opened 2024-03-07 19:20 UTC by MaxW1337

2024-03-08 15:10 UTC, AlexCuse requested changes
Thanks for waking this up, I threw it together in a couple hours one day and never looked again :sweat_smile: 

I have gotten more interested in pulsar as time goes on.  I remember running into problems trying to run the tests last time I tried but wonder if we could get this in shape to send back to ThreeDotsLabs as a supported pub/sub.

2024-03-08 15:10 UTC, AlexCuse commented on pkg/pulsar/subscriber.go
> +func (s *Subscriber) Subscribe(ctx context.Context, topic string, config SubscriptionConfig) (<-chan *message.Message, error) {
This deviates from the watermill Subscriber interface and probably causes problems - ideally these options would be passed in to the NewSubscriber function as part of SubscriberConfig and used internally.

2024-03-08 22:17 UTC, AlexCuse commented on pkg/pulsar/subscriber.go
> +func (s *Subscriber) Subscribe(ctx context.Context, topic string, config SubscriptionConfig) (<-chan *message.Message, error) {
This is a nice trick you can use to make sure you stay in sync while working https://github.com/ThreeDotsLabs/watermill-nats/blob/master/pkg/jetstream/subscriber.go#L18

2024-03-09 12:34 UTC, MaxW1337 commented on pkg/pulsar/subscriber.go
> +func (s *Subscriber) Subscribe(ctx context.Context, topic string, config SubscriptionConfig) (<-chan *message.Message, error) {
Oh yeah, didn't thought of the Subscriber interface. Thanks for pointing that out and the trick used in jetstream subscriber.

2024-08-04 12:59 UTC, AlexCuse approved these changes

2024-08-04 13:00 UTC, merged